### ISSUE TITLE
How to update bill

### ISSUE THREAD

**Issue by addictedderzthine** [better-reports/QuickBooksSharp#10]
I am trying to update the bill by using this code but looks like it doesn't work.

               ` var dataService = new DataService(token, long.Parse(realmId), useSandbox: true);
                var billResponse=( await dataService.QueryAsync<Bill>("SELECT * FROM Bill")).Response;
                if (billResponse != null)
                {
                    var bill = billResponse.Entities.FirstOrDefault();
              
                    // update bill here
                    bill.PrivateNote = "sample memo";
                    bill.Memo = "Memo";
                    await dataService.PostAsync(bill);
                }`

Any idea?

**Comment by clement911** [comment]
I tried it and the PrivateNote did get updated correctly.
The Memo field however is not supported on Bills so you can't update it.
