### ISSUE TITLE
Can't post memo on bill

### ISSUE THREAD

**Issue by adlartuten** [better-reports/QuickBooksSharp#14]
I am trying to upload a bill with a memo to QBO. The bill is showing up correctly however the memo is not. I see in the files that the transaction's Memo property is hidden by it's child PurchaseByVendor Memo property, but not sure if this is the error or not.

**Comment by clement911** [comment]
According to the [Bill API docs](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/bill), you must use the `PrivateNote` field to update the memo.

**Comment by adlartuten** [comment]
Ah, I apologize. Thank you for the clarification
