### ISSUE TITLE
QuickBooks Security Enhancement Features

### ISSUE THREAD

**Issue by webs1331** [better-reports/QuickBooksSharp#15]
https://blogs.intuit.com/2023/09/05/changes-to-identity-signature-keys-that-may-impact-your-application/

Hi, just wanted to see if this topic has been under your consideration @clement911 . It seems that QuickBooks is making some back-end change to their security flow on March 1st 2024. 

Thank you

**Comment by clement911** [comment]
QuickBooksSharp doesn't currently offer an API to validate these tokens, so there is nothing to change.

Reference: https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/openid-connect#validate-id-token

**Comment by webs1331** [comment]
I must've misunderstood their announcement. Thank you for the swift reply!

**Comment by clement911** [comment]
Sure thing 😀
