### ISSUE TITLE
Delete items such as Invoices?

### ISSUE THREAD

**Issue by theSnoMan1** [better-reports/QuickBooksSharp#16]
Is there any way to delete items such as invoices with QuickBooksSharp?  

Also, any plans to add additional properties to entities such as ProjectRef to Invoice?

(Thank you for your work by the way)

**Comment by clement911** [comment]
That was missing from 3.0 but please use the latest 3.1 for this.

There is an example here: https://github.com/better-reports/QuickBooksSharp?tab=readme-ov-file#delete-entities
