### ISSUE TITLE
Partial Classes

### ISSUE THREAD

**Issue by theSnoMan1** [better-reports/QuickBooksSharp#17]
Any chance entity classes could be marked as Partial so it's easier to write extensions for them? I don't know if you could somehow implement [NotMapped] (or similar) to prevent any custom properties from being sent to Quickbooks which would likely cause errors.  I use this method with EF scaffolded entities and SQL Server.

**Comment by clement911** [comment]
Partial classes can be define across multiple assemblies.
[NotMapped] is an EF concern that QuickBooksSharp is not concerned with.

I don't recommend perisiting QuickBooksSharp objects. Instead you should map to custom objects that you define
