### ISSUE TITLE
Refreshing Tokens

### ISSUE THREAD

**Issue by dgreenheck** [better-reports/QuickBooksSharp#18]
I do not seen a mechanism for refreshing the tokens (aside from instantiating a new `DataService`). There is also no way to update the tokens manually since the variables are private/protected and readonly.

This presents issues in an ASP.NET application where the `DataService` is injected, since there is no way to correctly re-instantiate an instance of `IDataService`.

**Comment by clement911** [comment]
Hi @dgreenheck , have you seen this doc?
https://github.com/better-reports/QuickBooksSharp?tab=readme-ov-file#refresh-token

**Comment by clement911** [comment]
Closing since haven't heard back
