### ISSUE TITLE
GetCDCAsync function consistently failing 

### ISSUE THREAD

**Issue by jakedoren** [better-reports/QuickBooksSharp#19]
"Operation cdc with changedSince date {date} which is older than fixed days is not supported." Error is happening consistently with this endpoint.

Looks to be because of DateTimeOffset rather than sending DateTime for "changedSince"

**Comment by clement911** [comment]
Can you please elaborate? I'm not quite sure what you mean.
We use GetCDCAsync without any such issues.

**Comment by clement911** [comment]
Closing but feel free to reopen if you can provide more details.
