### ISSUE TITLE
SalesTaxRateList not populated in TaxCode

### ISSUE THREAD

**Issue by cdubiel-promiles** [better-reports/QuickBooksSharp#20]
I'm not sure if I'm doing something wrong, but I'm trying to query all of the TaxCodes for my company, including the TaxRates in the SalesTaxRateList property, but none of the list objects seem to populate.

Is there a seperate call I need to make? It seems like (according to the QuickBooks documentation) this is how I'm supposed to get the combined TaxRates for TaxCodes with multiple TaxRates

**Comment by clement911** [comment]
Please elaborate

**Comment by cdubiel-promiles** [comment]
Nevermind, I did not see the populated "SalesTaxRateList" object for the tax code that contained a combination rate I was looking at. I found what I'm looking for:
![image](https://github.com/user-attachments/assets/20beabf2-1990-42e6-a749-91386b3ec20f)
