### ISSUE TITLE
URL for POSTing a TaxService is incorrect

### ISSUE THREAD

**Issue by cdubiel-promiles** [better-reports/QuickBooksSharp#21]
I believe the URL for POSTing a TaxService (the way to create new TaxCodes and TaxRates) is incorrect. 

[According to the documentation](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/taxservice#create-a-taxservice), the URL for POSTing a TaxService should be "/v3/company/{companyId}/taxservice/taxcode". The PostAsync method in the DataService is using GetEntityName to retrieve the object name (assuming entity classes are named after their endpoints) to form the URL to POST to.

So for the "TaxService" object, the URL is being created as "/v3/company/{companyId}/taxservice", which is missing the trailing "/taxcode" part.

I think we need a special case for the TaxService entity to return "taxservice/taxcode" instead of "taxservice".

**Comment by cdubiel-promiles** [comment]
I made a pull request: https://github.com/better-reports/QuickBooksSharp/pull/22

**Comment by clement911** [comment]
Thank you @cdubiel-promiles for your contribution.
It's now available in version 3.2.0
