### ISSUE TITLE
Does this support QuickBooks Desktop?

### ISSUE THREAD

**Issue by SoftCircuits** [better-reports/QuickBooksSharp#25]
I'm looking for the simplest way to add transactions to QuickBooks Desktop from my .NET Core application. But it seems no matter where I look, I eventually get into documentation that seems specific to QuickBooks online.

Does this library support QuickBooks desktop? It is still a good way to interface with QuickBooks?

**Comment by clement911** [comment]
I'm afraid it does not.
QuickBooksSharp is for QB Online only.
