### ISSUE TITLE
Hangs in .NET Framework 4.8

### ISSUE THREAD

**Issue by KalebAxon** [better-reports/QuickBooksSharp#26]
I am in the unhappy position of needing to use this in a legacy MVC 5 app. But when I call AuthenticationService.GetOAuthTokenAsync(), the task never completes.

Identical code works fine in .NET 8.

Any ideas?

**Comment by clement911** [comment]
Can you post a min repro?

**Comment by KalebAxon** [comment]
There was an issue in my code that could cause a deadlock, and for some reason it didn't happen in mvc core, so I thought it was a compatibility issue.
