### ISSUE TITLE
Clarification about README

### ISSUE THREAD

**Issue by amir734jj** [better-reports/QuickBooksSharp#27]
Quick question. README is a little confusing. Is `redirectUrl` in OAuth callback the same redirect URL that we provide [in here](https://github.com/better-reports/QuickBooksSharp?tab=readme-ov-file#generate-url-to-redirect-user-for-approval-of-connection) (e.g. https://myapp.com/quickbooks/authresult)

```csharp
[HttpGet]
public async Task<IActionResult> AuthResult(string code, long realmId, string state)
{
    //validate state parameter
    var authService = new AuthenticationService();
    string clientId = //get from config
    string clientSecret = //get from config
    var result = await authService.GetOAuthTokenAsync(clientId, clientSecret, code, redirectUrl); 
    //                                                                              ^^^ this ^^^
    ...
}
```

**Comment by clement911** [comment]
Yes.
I agree it's confusing, even in the QBO official docs.
The redirect uri is passed in when exchanging the oauth token. The user will not be redirected in this step though. I think it's just an extra verification by Intuit to ensure that it matches the redirect uri declared in the app configuration. See https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#add-uri
